import spacy # Importing the spacy library so that we can use its NLP tools such as tokenization, named entity recognition
# part-of-speech tagging, etc. 
import wikipedia 
nlp = spacy.load("en_core_web_sm") # Loading the small english language model (en_core_web_sm) provided by spaCy.
# pre-trained pipelines for English text 
from sentence_transformers import SentenceTransformer, util

# Load the pretrained model for sentence embedding 
model = SentenceTransformer('all-MiniLM-L6-v2')

def check_consistency(llm_response, retrieved_context): 
    # llm response: The output generated by the LLM 
    # retrieved_context: factual content retrieved from Wikipedia (or other trusted sources)
    embeddings = model.encode([llm_response, retrieved_context]) # This uses a preloaded SentenceTransformer model (like all-MiniLM-L6-v2) 
    # to convert both input strings into numerical vector representations called embeddings.
    score = util.cos_sim(embeddings[0], embeddings[1]) # Console similarity ranges from -1 to 1:
    # 1 = perfect semantic match | 0 = completely unrelated | -1 = opposite in meaning (rare for language) 
    return score.item() # This converts the single-value tensor score (from PyTorch) into a plain Python float.
    # the function returns a semantic similarity score (e.g., 0.86), which you can use to determine whether the response is trustworthy.

def extract_entities(text): # Function taking in a string as an argument 
    doc = nlp(text) # Passes the text through the pre-trained pipeline, variable name nlp
    # A doc object contains tokens, linguistic annotations, and most important, named entities.
    return [ent.text for ent in doc.ents if ent.label_ in ["GPE", "ORG", "PERSON", "LOC", "EVENT"]] # Goes through a list comprehension that goes through each entity in doc.ents
# ent.text = Exact text of the entity (Ex: "Toronto" or "Google")
# ent.label = Entity type "GPE" for location \, "ORG" for organization)
# It filters and returns only the entities whose labels are: 
# GPE: Geo-political entity (like countries and cities)
# ORG: Organizations (e.g., Microsoft)
# PERSON: Person names
# LOC: Non-GPE Locations (mountains, rivers, etc.)
# Event: Named events (e.g., "Olympics")
def retrieve_wikipedia_summary(entity): #One input parameter is a string that will typically be the name of a person, a place, or concept one wants to look up
    # on wikipedia
    try:
        return wikipedia.summary(entity, sentences=3) # We conduct the wikipedia search. wikipedia.summary. Entity -> The string you're searching for. sentence = 3 | Limit the result to the first 3 sentences of the summary.
    except: 
        return "" 

#Summary of code: 
# This function takes in a block of text and returns a list of meaningful named entities that are geographical, personal, organizational, or event-based.

