/**
 * AI Hallucination Detector - Content Script
 * 
 * Monitors web pages for AI-generated content, verifies factual claims against
 * trusted sources, and highlights potential hallucinations.
 */

class AIContentObserver {
  constructor() {
    // Configuration for AI content detection
    this.config = {
      // Monitor these DOM changes
      childList: true,
      subtree: true,
      characterData: true,
      
      // Optimize performance
      characterDataOldValue: false
    };

    // Elements/classes commonly used by AI platforms
    this.aiSelectors = [
      '.ai-generated',
      '.chatgpt-response',
      '.assistant-message',
      '[aria-label*="AI"]',
      '[data-source="bot"]',
      // Add more platform-specific selectors here
    ];

    // Minimum text length to analyze (avoid short snippets)
    this.MIN_TEXT_LENGTH = 20;

    // Initialize the observer
    this.observer = new MutationObserver(this.handleMutations.bind(this));
  }

  /**
   * Start monitoring the page for AI-generated content
   */
  start() {
    try {
      this.observer.observe(document.body, this.config);
      this.scanExistingContent();
      this.injectStyles();
      console.log('[RealityCheck] Monitoring for AI content...');
    } catch (error) {
      console.error('[RealityCheck] Observer failed:', error);
    }
  }

  /**
   * Scan existing DOM elements on page load
   */
  scanExistingContent() {
    this.aiSelectors.forEach(selector => {
      document.querySelectorAll(selector).forEach(element => {
        this.processElement(element);
      });
    });

    // Also check for generic AI indicators in text
    document.querySelectorAll('p, div, span').forEach(element => {
      if (this.isLikelyAIGenerated(element.textContent)) {
        this.processElement(element);
      }
    });
  }

  /**
   * Handle DOM mutations (new content added dynamically)
   */
  handleMutations(mutations) {
    for (const mutation of mutations) {
      for (const node of mutation.addedNodes) {
        // Skip non-element nodes
        if (node.nodeType !== Node.ELEMENT_NODE) continue;

        // Check if the node itself matches AI selectors
        if (this.matchesAISelector(node)) {
          this.processElement(node);
        }

        // Check child elements of added nodes
        this.aiSelectors.forEach(selector => {
          node.querySelectorAll?.(selector).forEach(element => {
            this.processElement(element);
          });
        });
      }
    }
  }

  /**
   * Check if an element matches known AI patterns
   */
  matchesAISelector(element) {
    return this.aiSelectors.some(selector => element.matches(selector));
  }

  /**
   * Heuristic check for AI-generated text patterns
   */
  isLikelyAIGenerated(text) {
    if (!text || text.length < this.MIN_TEXT_LENGTH) return false;

    const aiIndicators = [
      'as an AI language model',
      'generated by AI',
      'according to my knowledge cutoff',
      // Add more patterns as needed
    ];

    return aiIndicators.some(indicator => 
      text.toLowerCase().includes(indicator)
    );
  }

  /**
   * Process a potential AI-generated element
   */
  async processElement(element) {
    const text = element.textContent.trim();
    if (!text || text.length < this.MIN_TEXT_LENGTH) return;

    try {
      // Get context before analysis
      const context = this.getContext(element);

      // Send to background for verification
      const response = await chrome.runtime.sendMessage({
        action: 'ANALYZE_TEXT',
        text: text,
        context: context
      });

      if (response.success && response.data.flagged) {
        this.highlightIssues(element, response.data);
      }
    } catch (error) {
      console.error('[RealityCheck] Analysis failed:', error);
    }
  }

  /**
   * Capture contextual information about where the text appears
   */
  getContext(element) {
    return {
      // Page context
      url: window.location.href,
      title: document.title,
      domain: window.location.hostname,
      
      // Content context
      elementType: element.tagName,
      elementClass: element.className,
      surroundingText: this.getSurroundingText(element),
      
      // User context
      selection: window.getSelection().toString(),
      isSelected: element.contains(window.getSelection().anchorNode)
    };
  }

  /**
   * Get text surrounding the element (for better context understanding)
   */
  getSurroundingText(element, radius = 2) {
    const siblings = [];
    let prev = element.previousElementSibling;
    let next = element.nextElementSibling;
    
    for (let i = 0; i < radius; i++) {
      if (prev) {
        siblings.unshift(prev.textContent);
        prev = prev.previousElementSibling;
      }
      if (next) {
        siblings.push(next.textContent);
        next = next.nextElementSibling;
      }
    }
    
    return siblings.join(' [...] ');
  }

  /**
   * Highlight problematic text segments
   */
  highlightIssues(element, analysis) {
    // Create a document fragment to hold our changes
    const fragment = document.createDocumentFragment();
    let lastPos = 0;
    
    // Sort highlights by start position (reverse order to avoid offset issues)
    const sortedHighlights = [...analysis.highlights].sort((a, b) => b.start - a.start);
    
    // Process the original text node
    const textNode = element.firstChild?.nodeType === Node.TEXT_NODE 
      ? element.firstChild 
      : element;
    const originalText = textNode.textContent;
    
    // Split the text into highlighted and non-highlighted segments
    sortedHighlights.forEach(highlight => {
      // Create a span for the highlighted portion
      const highlightSpan = document.createElement('span');
      highlightSpan.className = 'ai-hallucination-highlight';
      highlightSpan.dataset.tooltip = this.createTooltipContent(highlight);
      
      // Add the text after the highlight
      if (highlight.end < originalText.length) {
        const afterText = document.createTextNode(
          originalText.substring(highlight.end, lastPos)
        );
        fragment.insertBefore(afterText, fragment.firstChild);
      }
      
      // Add the highlighted text
      const highlightText = document.createTextNode(
        originalText.substring(highlight.start, highlight.end)
      );
      highlightSpan.appendChild(highlightText);
      fragment.insertBefore(highlightSpan, fragment.firstChild);
      
      // Add the text before the highlight
      lastPos = highlight.start;
    });
    
    // Add any remaining text before the first highlight
    if (lastPos > 0) {
      const beforeText = document.createTextNode(
        originalText.substring(0, lastPos)
      );
      fragment.insertBefore(beforeText, fragment.firstChild);
    } else if (sortedHighlights.length === 0) {
      // No highlights - just use original text
      fragment.appendChild(document.createTextNode(originalText));
    }
    
    // Replace the original content
    element.replaceChild(fragment, textNode);
    
    // Add event listeners for tooltips
    this.addTooltipBehavior(element);
  }

  /**
   * Create tooltip content for a highlighted segment
   */
  createTooltipContent(highlight) {
    return `
      <div class="ai-tooltip">
        <strong>Potential Issue</strong>
        <p>Similarity: ${(highlight.similarity * 100).toFixed(1)}%</p>
        <p>Suggested Correction:</p>
        <blockquote>${highlight.matched_source.substring(0, 200)}...</blockquote>
        <button class="copy-suggestion">Copy Suggestion</button>
      </div>
    `;
  }

  /**
   * Add interactive tooltip behavior
   */
  addTooltipBehavior(element) {
    element.addEventListener('mouseover', (e) => {
      if (e.target.classList.contains('ai-hallucination-highlight')) {
        this.showTooltip(e.target, e.target.dataset.tooltip);
      }
    }, { passive: true });
    
    element.addEventListener('click', (e) => {
      if (e.target.classList.contains('copy-suggestion')) {
        this.copySuggestion(e);
      }
    });
  }

  /**
   * Display a tooltip for a highlighted segment
   */
  showTooltip(element, content) {
    // Remove existing tooltip if any
    this.removeTooltip();
    
    // Create new tooltip
    const tooltip = document.createElement('div');
    tooltip.className = 'ai-tooltip-container';
    tooltip.innerHTML = content;
    
    // Position near the highlighted text
    const rect = element.getBoundingClientRect();
    tooltip.style.position = 'absolute';
    tooltip.style.left = `${rect.left + window.scrollX}px`;
    tooltip.style.top = `${rect.bottom + window.scrollY + 5}px`;
    tooltip.style.zIndex = '9999';
    
    document.body.appendChild(tooltip);
    this.currentTooltip = tooltip;
    
    // Close tooltip when clicking outside
    setTimeout(() => {
      document.addEventListener('click', this.handleOutsideClick, { once: true });
    }, 100);
  }

  /**
   * Handle clicks outside the tooltip
   */
  handleOutsideClick = (e) => {
    if (!this.currentTooltip?.contains(e.target)) {
      this.removeTooltip();
    }
  };

  /**
   * Remove the current tooltip
   */
  removeTooltip() {
    if (this.currentTooltip) {
      this.currentTooltip.remove();
      this.currentTooltip = null;
    }
    document.removeEventListener('click', this.handleOutsideClick);
  }

  /**
   * Copy suggested correction to clipboard
   */
  copySuggestion(event) {
    const tooltip = event.target.closest('.ai-tooltip');
    const suggestion = tooltip.querySelector('blockquote')?.textContent;
    if (suggestion) {
      navigator.clipboard.writeText(suggestion.trim());
      event.target.textContent = 'Copied!';
      setTimeout(() => {
        event.target.textContent = 'Copy Suggestion';
      }, 2000);
    }
  }

  /**
   * Inject necessary CSS styles into the page
   */
  injectStyles() {
    const style = document.createElement('style');
    style.textContent = `
      .ai-hallucination-highlight {
        position: relative;
        background-color: rgba(255, 229, 100, 0.3);
        border-bottom: 2px dashed #FFE564;
        cursor: pointer;
      }
      
      .ai-hallucination-highlight:hover {
        background-color: rgba(255, 229, 100, 0.5);
      }
      
      .ai-tooltip-container {
        font-family: -apple-system, BlinkMacSystemFont, sans-serif;
        background: white;
        border: 1px solid #e1e1e1;
        border-radius: 8px;
        padding: 12px;
        max-width: 300px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        font-size: 14px;
        line-height: 1.4;
      }
      
      .ai-tooltip strong {
        color: #d32f2f;
      }
      
      .ai-tooltip blockquote {
        margin: 8px 0;
        padding: 8px;
        background: #f5f5f5;
        border-left: 3px solid #ccc;
        font-size: 13px;
      }
      
      .ai-tooltip button.copy-suggestion {
        background: #4285f4;
        color: white;
        border: none;
        padding: 4px 8px;
        border-radius: 4px;
        cursor: pointer;
        font-size: 12px;
        margin-top: 8px;
      }
    `;
    document.head.appendChild(style);
  }
}

// Start the observer when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => new AIContentObserver().start());
} else {
  new AIContentObserver().start();
}
